ci: updated rust workflow

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -1,41 +1,83 @@
 name: Rust
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
+
 permissions:
   contents: read
   actions: read
   checks: write
+
 env:
   CARGO_TERM_COLOR: always
+  CARGO_INCREMENTAL: 0
+
 jobs:
   build-and-test:
     name: Build and Test Rust crates
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+
     steps:
-    - uses: actions/checkout@v4
-    - name: Cache
-      uses: actions/cache@v4
-      with:
-        path: |
-          ~/.cargo/registry
-          ~/.cargo/git
-          target
-        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-    - name: Install cargo2junit
-      run: cargo install cargo2junit
-    - name: Build binaries in
-      run: cargo build
-    - name: Run tests and convert to JUnit format
-      run: RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format=json --report-time | tee test-results.json
-    - name: Convert test output to JUnit format
-      run: cat test-results.json | cargo2junit > test-results.xml
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: Tests report          # Name of the check run which will be created
-        path: test-results.xml      # Path to test results
-        reporter: java-junit        # Format of test results
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      # https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/rust.json
+      - name: Install Rust Problem Matcher
+        if: matrix.os == 'ubuntu-latest'
+        run: echo "::add-matcher::.github/rust.json"
+
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cargo/registry
+            ~/.cargo/git
+            target
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+
+      - name: Install cargo2junit
+        run: cargo install cargo2junit
+
+      - name: Bump opt-level
+        if: matrix.os == 'ubuntu-latest'
+        run: sed -i '/\[profile.dev]/a opt-level=1' Cargo.toml
+
+      - name: Codegen checks (pdf-analyzer)
+        run: cargo codegen --check
+
+      - name: Compile (tests)
+        run: cargo test --no-run --locked
+
+        # It's faster to `test` before `build` ¯\_(ツ)_/¯
+      - name: Compile (pdf-analyzer)
+        run: cargo build --quiet
+
+      - name: Run tests and convert to JUnit format (Unix)
+        if: runner.os != 'Windows'
+        run: RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format=json --report-time --quiet | tee test-results.json
+
+      - name: Run tests and convert to JUnit format (Windows)
+        if: runner.os == 'Windows'
+        run: |
+          $env:RUSTC_BOOTSTRAP=1
+          cargo test -- -Z unstable-options --format=json --report-time --quiet | tee test-results.json
+
+      - name: Convert test output to JUnit format
+        run: cat test-results.json | cargo2junit > test-results.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Tests report ${{ matrix.os }} # Name of the check run which will be created
+          path: test-results.xml # Path to test results
+          reporter: java-junit # Format of test results
